# serverless.yml

# Serverless.yml is the configuration the CLI uses to deploy your code to
# your provider of choice. The file denotes the entire architecture of the
# server, including the provider, the plugins, and the functions.

# Read the serverless docs here:
# https://serverless.com/framework/docs/

# The `service` block is the name of the service
service: wwf-lambda-sensui
# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  stage: develop
  region: us-west-1 
  iamRoleStatements:
    - Effect: Allow
      Action:
      - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
    - Effect: Allow
      Action:
      - s3:*
      Resource: 'arn:aws:s3:::*'

  environment:
      SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}

# Use the serverless-webpack plugin to transpile ES6

# serverless-kms-secrets: Serverless plugin to encrypt variables with KMS
# A Serverless Plugin for the Serverless Framework which helps with
# encrypting service secrets using the AWS Key Management Service (KMS)
plugins:
  #- serverless-webpack
  - serverless-kms-secrets

# Enable auto-packing of external modules
custom:
  #webpackIncludeModules: true
  serverless-kms-secrets:
    secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
# The `functions` block defines what code to deploy
functions:
  testEndpoint:
    handler: handler.testEndpoint
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: testEndpoint
          method: get
  testEndpoint2:
    handler: handler.testEndpoint
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: testEndpoint2
          method: get
          cors: true
  allProjectDet:
    handler: handler.allProjectDet
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: allProjectDet
          method: get
          cors: true
  projectDet:
    handler: handler.projectDet
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: projectDet
          method: post
          cors: true
  createProject:
    handler: handler.createProject
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: createProject
          method: post
          cors: true
  createUser:
    handler: handler.createUser
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: createUser
          method: post
          cors: true
  user:
    handler: handler.user
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: user
          method: post
          cors: true
  promoteProject:
    handler: handler.promoteProject
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: promoteProject
          method: post
          cors: true
  confirmProject:
    handler: handler.confirmProject
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: confirmProject
          method: post
          cors: true
  revertPromoteProject:
    handler: handler.revertPromoteProject
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: revertPromoteProject
          method: post
          cors: true
  createAccount:
    handler: handler.createAccount
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: createAccount
          method: post
          cors: true
  challenge:
    handler: handler.challenge
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: challenge
          method: post
          cors: true
  confirmChallenge:
    handler: handler.confirmChallenge
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: confirmChallenge
          method: post
          cors: true
  watchEvent:
    handler: handler.watchEvent
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: watchEvent
          method: get
          cors: true
  integratePromoteWatch:
    handler: handler.integratePromoteWatch
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: integratePromoteWatch
          method: post
          cors: true
    timeout: 120
  commitVote:
    handler: handler.commitVote
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: commitVote
          method: post
          cors: true
  test1:
    handler: handler.test1
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: test1
          method: post
          cors: true
  confirmTx:
    handler: handler.confirmTx
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: confirmTx
          method: post
          cors: true
  sleep:
    handler: handler.sleep
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: sleep
          method: post
          cors: true
    timeout: 30



