# serverless.yml

# Serverless.yml is the configuration the CLI uses to deploy your code to
# your provider of choice. The file denotes the entire architecture of the
# server, including the provider, the plugins, and the functions.

# Read the serverless docs here:
# https://serverless.com/framework/docs/

# The `service` block is the name of the service
service: wwf-lambda-sensui
# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  stage: develop
  region: us-west-1 
  iamRoleStatements:
    - Effect: Allow
      Action:
      - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
    - Effect: Allow
      Action:
      - s3:*
      Resource: 'arn:aws:s3:::*'

  environment:
      SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}

# Use the serverless-webpack plugin to transpile ES6

# serverless-kms-secrets: Serverless plugin to encrypt variables with KMS
# A Serverless Plugin for the Serverless Framework which helps with
# encrypting service secrets using the AWS Key Management Service (KMS)
plugins:
  #- serverless-webpack
  - serverless-kms-secrets

# Enable auto-packing of external modules
custom:
  #webpackIncludeModules: true
  serverless-kms-secrets:
    secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
  allProjectDet:
    handler: handler.allProjectDet
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: allProjectDet
          method: get
          cors: true
  projectDet:
    handler: handler.projectDet
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: projectDet
          method: post
          cors: true
  createProject:
    handler: handler.createProject
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: createProject
          method: post
          cors: true


